spring:
  datasource:
    url: jdbc:mysql://47.105.148.90:3306/stock?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Dream1226.27!

  redis:
    host: 47.105.148.90
    port: 6399
    database: 0
    password:
    max-idle: 8
    max-active: 8
    max-wait: -1
    min-idle: 0
    timeout: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://124.222.217.230:8001/eureka/


xxl:
  job:
    admin:
      addresses: http://124.222.217.230:9001/xxl-job-admin
    accessToken:
    executor:
      appname: xxl-job-stock
      address: 124.222.217.230
      ip:
      port: 8888
      logretentiondays: 30
      #      logpath: /Users/coatardbul/Desktop/xxljob
      logpath: /usr/local/xxl_job/client
