spring:
  datasource:
    url: jdbc:mysql://47.105.148.90:3306/stock?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Dream1226.27!
  redis:
    host: 47.105.148.90
    port: 6399
    database: 0
    password:
    max-idle: 8
    max-active: 8
    max-wait: -1
    min-idle: 0
    timeout: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://124.222.217.230:8001/eureka/


xxl:
  job:
    admin:
      addresses: http://124.222.217.230:9001/xxl-job-admin
    accessToken:
    executor:
      appname: xxl-job-stock
      address: 124.222.217.230
      ip:
      port: 8888
      logretentiondays: 30
      #      logpath: /Users/coatardbul/Desktop/xxljob
      logpath: /usr/local/xxl_job/client


##邮箱发送服务，sendFrom 发送邮箱，sendFromAuthCode 邮箱授权码，不是密码！！
##emailProp 邮箱服务器 verifyCodeOutServiceTime 邮箱失效时间（分钟）
##verifyCodeLength 验证码长度
email:
  service:
    sendFrom: 953903969@qq.com
    sendFromAuthCode: lsgajdcdlzhqbcih
    emailProp: smtp.qq.com



##腾讯云对象存储
cos:
  baseUrl: https://stable-up-1254163062.cos.ap-nanjing.myqcloud.com
  secretId: AKIDc4JL8gy1oNhmbAUYNwGK9i26vWyB9uPf
  secretKey: 3qOhkX5OREl36uUrzrUryqSovnPlriKK
  regionName: ap-nanjing
  bucketName: stable-up-1254163062
  folderPrefix: /files
